# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: zinc

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Guillem Vidal Lorda'
    description: 'Guillem Vidal Lorda - Social scientist and policy advisor working at the intersection of political economy and public policy. Research on inequality, welfare, and socioeconomic policy.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: false
    logo:
      text: "Guillem Vidal Lorda"

# Site footer
footer:
  copyright:
    notice: '© {year} Guillem Vidal Lorda'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
